name: "CAN to MQTT Bridge Repository"
url: 'https://github.com/Backroads4Me/can-mqtt-bridge'
maintainer: "Ted Lanham <tedlanham@gmail.com>"
description: "Home Assistant add-on repository for CAN bus integration via MQTT"
homeassistant: "2025.1.0"
location: "."
release: "stable"